// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial.Repository;

namespace Parcial.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191014030549_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parcial.Domain.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo");

                    b.Property<int>("JugadorId");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Parcial.Domain.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JugadorId");

                    b.Property<int>("Puesto");

                    b.Property<int>("TorneoId");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Parcial.Domain.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<int>("Edad");

                    b.Property<string>("Nickname");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Parcial.Domain.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaInic");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreJuego");

                    b.Property<int>("Premio");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("Parcial.Domain.Cuenta", b =>
                {
                    b.HasOne("Parcial.Domain.Jugador")
                        .WithOne("Cuenta")
                        .HasForeignKey("Parcial.Domain.Cuenta", "JugadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Parcial.Domain.Inscripcion", b =>
                {
                    b.HasOne("Parcial.Domain.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Parcial.Domain.Torneo", "Torneo")
                        .WithMany()
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
